### ISSUE TITLE
blocking code in Chapter 7 only removed partially

### ISSUE THREAD

**Issue by Miles-Ahead-Digital** [PacktPublishing/Hands-On-Microservices-with-Spring-Boot-and-Spring-Cloud#15]
is there a reason why the blocking code in Chapter 7 is only replaced partially?
For example in  ProductServiceImp the method getProduct is refactored but the createProduct / deleteProduct is still blocking:

return newEntity.**block()**;

repository.findByProductId(productId).log().map(e -> repository.delete(e)).flatMap(e -> e).**block()**;

**Comment by magnus-larsson** [comment]
Hello!

Thanks for your question, it is a very relevant one!

I have tried to explain it on page 218 (in the PDF) as:

"_Since our message processor is based on a blocking programming model, we need to call the block() method on the returned Mono object from the persistence layer before we return it to the message processor. If we don't call the block() method, we won't be able to trigger the error handling in the messaging system if the processing in the service implementation fails; the event will not be requeued, and eventually, it will be moved to the dead-letter queue, as expected._"

So, due to how Spring Cloud Stream works, in the version used, we need to wait for the result before we return the call in the message processor. Otherwise, errors in the processing would be ignored silently.

However, I think I have failed to place the call to the `block()` method correctly. It should really be done in the message processor, that is the one that needs to wait, and not in the `createProduct` method. As it is done makes the `createProduct` method less reusable :-(

It should be a fairly simple refactoring exercise to change the signature of the `createProduct` method to return `Mono<Product>` instead of `Product`.

I hope this answers your question, if not please let me know!

Regards,
Magnus.

**Comment by Miles-Ahead-Digital** [comment]
Hi Magnus,

I just read the paragraph you mentioned and I'm wondering if it its possible to create a non blocking message processor?  (your advise is just a little relief on this topic..)

It would be nice to get a refactoring done because 
@EnableBinding(Sink.class)
 @StreamListener(target = Sink.INPUT)
is deprecated in the current version of org.springframework.cloud

checkout: https://stackoverflow.com/questions/65441549/enablebinding-is-deprecated-in-spring-cloud-stream-3-x
it seems that it now non-blocking.. if you look at the example implementation https://github.com/HabeebCycle/spring-cloud-stream-implemention 

Best regards
Stefan

**Comment by magnus-larsson** [comment]
Hello again Stefan!

Yes, I'm aware of this, but I can't change the code of this book to use new versions of Spring Cloud.

Also, from what I've learned for the new functional support in Spring Cloud Stream, I suffers the same problem with triggering the error mechanisms in the underlying messaging system (e.g. retry and DLQ handling) when a Mono/Flux is returned.

**Comment by Miles-Ahead-Digital** [comment]
Thanks
