### ISSUE TITLE
Question about Code Change in Chapter 13 - Retry Mechanism

### ISSUE THREAD

**Issue by Miles-Ahead-Digital** [PacktPublishing/Hands-On-Microservices-with-Spring-Boot-and-Spring-Cloud#16]
Hi Magnus,

can you explain the change in the screenshot:

![](https://user-images.githubusercontent.com/58099738/108320660-5f844f00-71c3-11eb-9632-7b1368fd4f15.png)

Is the retry mechanism still active (and only implicit executed by annotation) or did you remove it?
Best regards
Stefan

**Comment by magnus-larsson** [comment]
Hello Stefan!

Yes, it is still active!

This code change comes from fixing issue #8, i.e. upgrading the codebase to use SpringFox 3.0.0.

You can read about it the projects README.md file: https://github.com/PacktPublishing/Hands-On-Microservices-with-Spring-Boot-and-Spring-Cloud#source-code-changes

If you navigate to the documentation of this change, you can read in the section: https://github.com/PacktPublishing/Hands-On-Microservices-with-Spring-Boot-and-Spring-Cloud/blob/master/README_SpringFox-3.0.0_SpringBoot-2.3.2_SpringCloud-Hoxton-SR6.md#2332-updated-exception-classes that:

"The exception class CallNotPermittedException is replaced by the exception class CircuitBreakerOpenException, and we no longer need to catch and unwrap the exception class RetryExceptionWrapper."

This is due to the upgrade to Resilience 1.3.1 required by the upgrade to SpringFox 3.0.0.

I hope that answers your question?

Best regards,
Magnus.
