### ISSUE TITLE
Chapter-04 : No active profile set, falling back to default profiles: default

### ISSUE THREAD

**Issue by sandeeptiwari** [PacktPublishing/Hands-On-Microservices-with-Spring-Boot-and-Spring-Cloud#28]
I am using same code base and following same steps but facing no profile is being set  

![image](https://user-images.githubusercontent.com/1938049/133934828-5dacbada-7359-45f6-a2bf-d956a91735b5.png)

**Comment by magnus-larsson** [comment]
The source code for this book is based on Spring Boot 2.3 and the Hoxton release of Spring Cloud. Later versions of both Spring Boot and Spring Cloud require changes in the source code to work properly. One of them is to change the name of the property that specifies what Spring Profile settings are used in property files as described in https://spring.io/blog/2020/08/14/config-file-processing-in-spring-boot-2-4, see section "Profile Specific Documents". You can still use the old name, but then you will get a warning like: 

Property 'spring.profiles' imported from location 'class path resource [application.yml]' is invalid and should be replaced with 'spring.config.activate.on-profile'

Since you don't have any warning in the log output above, I suggest that you check the property name you use to specify the Spring profile in the `application.yml` file. Make sure it is set to `spring.config.activate.on-profile`. 

The [second edition of my book](https://www.amazon.com/gp/product/B094DMGZ6T) is based on Spring Boot 2.5.2 and Spring Cloud 2020.0.3 so if the property name doesn't seem to be the problem, I suggest that you check out the source code of the 2nd edition available at https://github.com/PacktPublishing/Microservices-with-Spring-Boot-and-Spring-Cloud-2E.

**Comment by shruthis-shetty** [comment]
Hi @sandeeptiwari , I hope you got the solution to your issue. Please let us know whether your problem got solved or not.

**Comment by sandeeptiwari** [comment]
Hi @magnus-larsson  @shruthis-shetty 

Actually I am following 2nd edition Since I bought new book from amazon.

![image](https://user-images.githubusercontent.com/1938049/134208315-3d9f7048-4b2e-4738-b11e-8ab87adde8a5.png)


I followed all steps mentioned in book but still its not picking docker profile.

While in other hand in my other project when I  put 

![image](https://user-images.githubusercontent.com/1938049/134208685-300ddbe2-c3ce-4989-b259-0ecce539f24f.png)
 in pom project, I was able to change profile


Please suggest what I am missing in your code?

**Comment by sandeeptiwari** [comment]
@magnus-larsson  @shruthis-shetty  Issue have been resolved, thanks for your support

**Comment by magnus-larsson** [comment]
Ok, I'll close the issue!
